# cloudbuild.yaml
steps:
# 1. Run tests (CI)
- name: 'python:3.11'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      pip install -r app/requirements.txt
      python3 -m pytest test_app.py

# 2. Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/modified-wonder-468716-e8/my_repo/flask-app:$SHORT_SHA'
    - './app'

# 3. Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/modified-wonder-468716-e8/my_repo/flask-app:$SHORT_SHA'

# 4. Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud run deploy flask-app \
        --image us-central1-docker.pkg.dev/modified-wonder-468716-e8/my_repo/flask-app:$SHORT_SHA \
        --region us-central1 \
        --platform managed \
        --allow-unauthenticated
