# Dockerfile
FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

# Use gunicorn to serve the Flask app
CMD ["gunicorn", "-b", "0.0.0.0:8080", "main:app"]
